[views]
[views.is_empty]
key = "unbeantwortet"
header = "# Nicht beantwortete Fragen"
title_de = "nicht_beantwortete_fragen"
help_de = "zeigt alle Fragen an, die noch ohne Antwort sind"
condition_start = "{% if val is None %}"
condition_end = "{% endif %}"
display_answer = false

[views.not_empty]
key = "beantwortet"
header = "# Beantwortete Fragen"
title_de = "beantwortete_fragen"
help_de = "zeigt alle Fragen an, die bisher beantwortet worden sind"
condition_start = "{% if val is not None %}"
condition_end = "{% endif %}"
display_answer = true

[views.beruecksichtigtes]
key = "beruecksichtigtes"
header = "# Berücksichtigtes"
title_de = "beruecksichtigtes"
help_de = "zeigt alle Fragen an, die mit 'beruecksichtigt' beantwortet worden sind"
condition_start = "{% if val.value == 'berücksichtigt' %}"
condition_end = "{% endif %}"
display_answer = false

[views.trifft_nicht_zu]
key = "trifft_nicht_zu"
header = "# Nicht Zutreffendes"
title_de = "nicht_zutreffendes"
help_de = "zeigt alle Fragen an, die mit 'trifft nicht zu' beantwortet worden sind"
condition_start = "{% if val.value == 'trifft nicht zu' %}"
condition_end = "{% endif %}"
display_answer = false

[template]
prefix = """
{% load view_tags %}
{% get_set 'm1' as m1 %}
"""