[views]
[views.is_empty]
key = "unbeantwortet"
header = "# Nicht beantwortete Fragen"
title_de = "nicht_beantwortete_fragen"
help_de = "zeigt alle Fragen an, die noch ohne Antwort sind"
condition_start = "{% if val is None %}"
condition_end = "{% endif %}"
display_answer = false

[views.not_empty]
key = "beantwortet"
header = "# Beantwortete Fragen"
title_de = "beantwortete_fragen"
help_de = "zeigt alle Fragen an, die bisher eantwortet worden sind"
condition_start = "{% if val is not None %}"
condition_end = "{% endif %}"
display_answer = true

[template]
prefix = """
{% load view_tags %}
{% get_set 'm1' as m1 %}
"""