# be aware that the trailing slashes are required
urls = [
    "api/v1/domain/attributes/",
    "api/v1/domain/attributes/export/",
    "api/v1/conditions/conditions/",
    "api/v1/conditions/conditions/export/",
    "api/v1/options/optionsets/",
    "api/v1/options/optionsets/export/",
    "api/v1/tasks/tasks/",
    "api/v1/tasks/tasks/export/",
    "api/v1/views/views/",
    "api/v1/views/views/export/",
    "api/v1/questions/catalogs/",
    "api/v1/questions/catalogs/export/",
    "api/v1/projects/projects/"
]

url_project="projects/1/export/xml/"

host = "http://localhost:8280"
docker_name="rdmo"
manage_py = "/home/rdmo/rdmo-app/manage.py"
